name: Build binary

on:
  workflow_dispatch:
    inputs:
      NCS_VERSION:
        description: "NCS SDK version. Ex. v2.6.1."
        required: true
        type: string
        default: "v2.6.1"
      BOARD:
        description: "Target board."
        required: true
        type: string
        default: nrf52dk_nrf52832

  workflow_call:
    inputs:
      NCS_VERSION:
        required: true
        type: string
      BOARD:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ inputs.NCS_VERSION }}

    env:
      NCS_ROOT: /opt/ncs/${{ inputs.NCS_VERSION }}

    steps:
      - name: Setup West workspace
        run: |
          west init -m https://github.com/$GITHUB_REPOSITORY .
          west update --narrow -o=--depth=1
          west zephyr-export
          pip3 install -r deps/zephyr/scripts/requirements-base.txt

      - name: Build with West
        run: |
          west build -p -b ${{ inputs.BOARD }} app/

      - name: Create filename prefix
        run: echo "PREFIX=${{ github.event.repository.name }}-${{ inputs.BOARD }}" >> "$GITHUB_ENV"

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v3.0

      - name: Prepare artifacts
        run: |
          cd build/zephyr
          mkdir -p artifacts
          mv zephyr.bin ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.bin
          mv zephyr.elf ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.elf
          mv zephyr.hex ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.hex

      # Run IDs are unique per repo but are reused on re-runs
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts_${{ github.run_id }}
          path: |
            build/zephyr/artifacts/*
