name: Build NRF Connect SDK Application

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ncs_version:
        description: "NCS SDK version (e.g., v2.6.2)"
        required: true
        default: "v2.6.2"
        type: string
      board:
        description: "Target board (e.g., nrf52dk_nrf52832)"
        required: true
        default: "nrf52dk_nrf52832"
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.2
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        shell: bash
    steps:
      - name: Checkout repository with BLE Beacon application
        uses: actions/checkout@v4
        with:
          path: zephyr_dev
      - name: Prepare west project       
        run: |
          export PATH=$PATH:${HOME}/.local/bin
          west init -l zephyr_dev
          west update -o=--depth=1 -n
          apt-get -y update
          apt-get -y install build-essential
      - name: Build firmware
        run: |
          cd zephyr_dev
          west build --build-dir build . --pristine -DBOARD_ROOT=. -DNCS_TOOLCHAIN_VERSION=NONE  -DCACHED_CONF_FILE=prj.conf --board nrf52dk_nrf52832
      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: zephyr_dev
          path: zephyr_dev/build/zephyr/zephyr_dev.hex
