name: Build NRF Connect SDK Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          export ZEPHYR_BASE=$PWD/zephyr
          export NRF_BASE=$PWD/nrf
          echo "ZEPHYR_BASE=$ZEPHYR_BASE" >> $GITHUB_ENV
          echo "NRF_BASE=$NRF_BASE" >> $GITHUB_ENV
          
      - name: Install west
        run: |
          pip install west

      - name: Update west
        run: |
          west init -l $NRF_BASE
          west update

      - name: Build application
        run: |
          west build -b nrf52dk_nrf52832 .


      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/zephyr/bin/*
