name: Build NRF Connect SDK Application

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ncs_version:
        description: "NCS SDK version (e.g., v2.6.2)"
        required: true
        default: "v2.6.2"
        type: string
      board:
        description: "Target board (e.g., nrf52dk_nrf52832)"
        required: true
        default: "nrf52dk_nrf52832"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ inputs.ncs_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          export ZEPHYR_BASE=$PWD/zephyr
          export NRF_BASE=$PWD/nrf
          echo "ZEPHYR_BASE=$ZEPHYR_BASE" >> $GITHUB_ENV
          echo "NRF_BASE=$NRF_BASE" >> $GITHUB_ENV

      - name: Install west
        run: pip install west

      - name: Update west
        run: |
          west init -l $NRF_BASE
          west update

      - name: Build application
        run: |
          west build -b ${{ inputs.board }} . || exit 1

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-${{ inputs.ncs_version }}-${{ inputs.board }}
          path: build/zephyr/bin/*
